# -*- coding: utf-8 -*-
"""nextgenfinal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFvmpdJ4zFg-7ABE9ueuV6H5DlYZVFGa
"""

import argparse
import os
import random
import time

import numpy as np
import pandas as pd
import matplotlib

# Establece el backend de Matplotlib para que las figuras se puedan guardar sin una interfaz gráfica.
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
# scipy.stats.wilcoxon se usa para pruebas estadísticas no paramétricas.
from scipy.stats import wilcoxon
# RandomForestClassifier para el modelo de aprendizaje automático.
from sklearn.ensemble import RandomForestClassifier
# Para visualizar la matriz de confusión, que ayuda a entender el rendimiento del clasificador.
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# ----------------------------------------------------------------------
# Constantes
# ----------------------------------------------------------------------
# Heurísticas disponibles para resolver el problema de la mochila.
HEURISTICS = ["DEF", "MAXP", "MAXPW", "MINW"]
# Mapea cada heurística a un índice numérico para uso interno (ej. en el modelo de RF).
H_TO_IDX = {h: i for i, h in enumerate(HEURISTICS)}
# Índice de la heurística MAXPW, que se usa como política base.
MAXPW_IDX = H_TO_IDX["MAXPW"]

# Nombres de las características dinámicas del estado que se usan para entrenar el modelo.
FEATURE_NAMES = [
    "mean_ratio_norm", "max_ratio_pack", "std_ratio_pack",
    "frac_packable", "tightness", "fill", "slack_per_item",
    "frac_items_left",
]

# Semilla para la reproducibilidad de los resultados aleatorios.
SEED = 42
# Umbral de confianza para el Random Forest Hyper-Heuristic (RF-HH).
# Si la probabilidad de la clase predicha es menor que este umbral, se recurre a MAXPW.
CONFIDENCE_THRESHOLD = 0.6
# Número de árboles en el Random Forest.
N_ESTIMATORS = 300
# Número mínimo de muestras requeridas para estar en un nodo hoja.
MIN_SAMPLES_LEAF = 10
# Argumentos clave para guardar las figuras (resolución, ajuste de diseño).
FIG_KW = dict(dpi=300, bbox_inches="tight")


# ----------------------------------------------------------------------
# Estado del problema (basado en arrays, no necesita deepcopy)
# ----------------------------------------------------------------------
class KnapsackState:
    """Estado de la mochila 0/1 basado en arrays.

    Los ítems se almacenan una vez como arrays de numpy; el proceso de resolución solo
    modifica `remaining` (máscara booleana) y `capacity`. Así, simular un
    rollout es una operación barata de guardar/restaurar esos dos valores en lugar de una
    copia profunda de todo el objeto.
    """

    __slots__ = ("weights", "profits", "ratios", "ratio_order",
                 "remaining", "capacity", "initial_capacity",
                 "n_items", "profit")

    def __init__(self, weights, profits, capacity):
        # Pesos de los ítems.
        self.weights = np.asarray(weights, dtype=np.int64)
        # Beneficios de los ítems.
        self.profits = np.asarray(profits, dtype=np.int64)
        # Razón beneficio/peso de cada ítem.
        self.ratios = self.profits / self.weights
        # Orden de los ítems basado en la razón beneficio/peso (de mayor a menor).
        # Se usa un ordenamiento estable para romper empates por el índice original.
        self.ratio_order = np.argsort(-self.ratios, kind="stable")
        # Número total de ítems.
        self.n_items = len(self.weights)
        # Máscara booleana que indica qué ítems aún no han sido empacados.
        self.remaining = np.ones(self.n_items, dtype=bool)
        # Capacidad actual de la mochila.
        self.capacity = int(capacity)
        # Capacidad inicial de la mochila (útil para el cálculo de características).
        self.initial_capacity = int(capacity)
        # Beneficio total acumulado en la mochila.
        self.profit = 0

    # -- E/S -----------------------------------------------------------
    @classmethod
    def from_file(cls, path: str) -> "KnapsackState":
        """Carga un estado del problema de la mochila desde un archivo.

        El archivo debe tener la primera línea con 'num_items, capacity'
        y las siguientes líneas con 'weight, profit' por cada ítem.
        """
        with open(path) as f:
            lines = f.readlines()
        # Lee el número de ítems y la capacidad de la primera línea.
        n_items, capacity = (int(x.strip()) for x in lines[0].split(","))
        weights, profits = [], []
        # Lee los pesos y beneficios de los ítems de las líneas siguientes.
        for i in range(n_items):
            w, p = lines[i + 1].split(",")
            weights.append(int(w.strip()))
            profits.append(int(float(p.strip())))
        return cls(weights, profits, capacity)

    # -- Selección de ítems por heurística -------------------------------
    def next_item(self, heuristic: str) -> int:
        """Devuelve el índice del ítem que la heurística empacaría a continuación, o -1 si no hay ninguno.

        Args:
            heuristic (str): El nombre de la heurística a usar ('DEF', 'MAXP', 'MAXPW', 'MINW').

        Returns:
            int: El índice del siguiente ítem a empacar, o -1.
        """
        # Encuentra los ítems que aún no han sido empacados y caben en la mochila.
        fits = self.remaining & (self.weights <= self.capacity)
        # Si no hay ítems que quepan, devuelve -1.
        if not fits.any():
            return -1
        # Obtiene los índices de los ítems que caben.
        idx = np.flatnonzero(fits)

        # Aplica la lógica de cada heurística:
        if heuristic == "DEF": # Default (el primer ítem que cabe).
            return int(idx[0])
        if heuristic == "MAXP": # Máximo Beneficio (el ítem con mayor beneficio).
            return int(idx[np.argmax(self.profits[idx])])
        if heuristic == "MAXPW": # Máxima Razón Beneficio/Peso (el ítem con mayor razón p/w).
            return int(idx[np.argmax(self.ratios[idx])])
        if heuristic == "MINW": # Mínimo Peso (el ítem con menor peso).
            return int(idx[np.argmin(self.weights[idx])])
        raise ValueError(f"Heurística desconocida: {heuristic}")

    def pack(self, item: int) -> None:
        """Empaca un ítem en la mochila, actualizando el estado.

        Args:
            item (int): El índice del ítem a empacar.
        """
        # Marca el ítem como no disponible.
        self.remaining[item] = False
        # Reduce la capacidad de la mochila.
        self.capacity -= int(self.weights[item])
        # Aumenta el beneficio total.
        self.profit += int(self.profits[item])

    # -- Completado rápido con MAXPW (usado por el rollout) --------------
    def maxpw_completion_profit(self) -> int:
        """Calcula el beneficio total después de completar el estado actual de forma voraz con MAXPW.

        Iterar la lista de ítems preordenada por razón beneficio/peso y empacar lo que quepa
        es equivalente a seleccionar repetidamente el ítem con mejor razón que quepa;
        el estado en sí no se modifica.

        Returns:
            int: El beneficio total (actual + el obtenido por la completación MAXPW).
        """
        cap = self.capacity
        extra = 0 # Beneficio adicional de la completación.
        w, p, rem = self.weights, self.profits, self.remaining
        for j in self.ratio_order:
            if rem[j] and w[j] <= cap: # Si el ítem restante cabe.
                cap -= w[j]
                extra += p[j]
        return self.profit + extra

    # -- Solucionadores --------------------------------------------------
    def solve_static(self, heuristic: str) -> int:
        """Resuelve el problema de la mochila usando una heurística estática (repetitiva).

        Args:
            heuristic (str): La heurística a usar.

        Returns:
            int: El beneficio final obtenido.
        """
        item = self.next_item(heuristic)
        while item != -1:
            self.pack(item)
            item = self.next_item(heuristic)
        return self.profit


# ----------------------------------------------------------------------
# Política de Rollout
# ----------------------------------------------------------------------
def rollout_choice(state: KnapsackState, base: str = "MAXPW",
                   prefer_base_on_ties: bool = False) -> str:
    """Determina la mejor heurística para el paso actual según la política de rollout.

    Cada heurística empaca un ítem; los ítems restantes se completan
    con la política base (MAXPW). Dado que MAXPW está entre los candidatos,
    el beneficio del rollout nunca es inferior al beneficio del MAXPW puro
    (propiedad de mejora secuencial, Bertsekas et al. 1997).

    Args:
        state (KnapsackState): El estado actual del problema de la mochila.
        base (str): La heurística base para la completación del rollout.
        prefer_base_on_ties (bool): Si True, cuando la heurística base empata
            con el mejor beneficio simulado, se devuelve la base. Usar True para
            ETIQUETAR datos de entrenamiento (evita etiquetas espurias por
            empates) y False al usar el rollout como método de solución.

    Returns:
        str: El nombre de la heurística que produce el mejor resultado en este paso.
    """
    best_h, best_profit = base, -1 # Inicializa con la heurística base.
    base_profit = -1
    for h in HEURISTICS:
        # Simula la selección de un ítem con la heurística actual.
        item = state.next_item(h)
        if item == -1: # Si la heurística no puede empacar nada en este paso.
            continue
        # Simular: empacar el ítem, evaluar la completación, restaurar el estado.
        state.pack(item) # Empaca temporalmente el ítem.
        total = state.maxpw_completion_profit() # Calcula el beneficio total con la completación MAXPW.
        # Deshace el empacado para restaurar el estado original.
        state.remaining[item] = True
        state.capacity += int(state.weights[item])
        state.profit -= int(state.profits[item])
        if h == base:
            base_profit = total
        # Si este resultado es mejor que el actual mejor, actualiza.
        if total > best_profit:
            best_profit, best_h = total, h
    # Desempate: si la base logra el mismo beneficio que la mejor, prefiere la base.
    if prefer_base_on_ties and base_profit == best_profit:
        return base
    return best_h


def solve_rollout(state: KnapsackState, base: str = "MAXPW") -> int:
    """Resuelve el problema de la mochila usando la política de rollout.

    En cada paso, usa `rollout_choice` para decidir la mejor heurística.

    Args:
        state (KnapsackState): El estado inicial del problema de la mochila.
        base (str): La heurística base para la completación en `rollout_choice`.

    Returns:
        int: El beneficio final obtenido.
    """
    while state.remaining.any(): # Mientras queden ítems por considerar.
        h = rollout_choice(state, base) # Elige la mejor heurística para este paso.
        item = state.next_item(h) # Obtiene el ítem seleccionado por esa heurística.
        if item == -1: # Si no se puede empacar más ítems.
            break
        state.pack(item) # Empaca el ítem seleccionado.
    return state.profit


# ----------------------------------------------------------------------
# Características dinámicas del estado (Sección 3.2 del artículo)
# ----------------------------------------------------------------------
def step_features(state: KnapsackState) -> list[float]:
    """Calcula un conjunto de características dinámicas del estado actual del problema de la mochila.

    Estas características se usan como entrada para el modelo de aprendizaje automático.

    Args:
        state (KnapsackState): El estado actual del problema de la mochila.

    Returns:
        list[float]: Una lista de valores de las características.
    """
    rem = state.remaining # Máscara de ítems restantes.
    if not rem.any(): # Si no quedan ítems, todas las características son 0.
        return [0.0] * len(FEATURE_NAMES)

    # Filtra pesos, beneficios y razones para los ítems restantes.
    w = state.weights[rem].astype(float)
    p = state.profits[rem].astype(float)
    r = p / w
    # Razón máxima, normalizada para evitar divisiones por cero.
    rmax = r.max() if r.max() > 0 else 1.0
    n = len(w) # Número de ítems restantes.
    cap = state.capacity # Capacidad restante.

    fits = w <= cap # Ítems restantes que caben en la mochila.
    if fits.any():
        pr = r[fits] # Razones de los ítems que caben.
        # Característica: Razón máxima p/w de ítems empacables, normalizada.
        max_ratio_pack = pr.max() / rmax
        # Característica: Desviación estándar de razones p/w de ítems empacables, normalizada.
        std_ratio_pack = pr.std() / rmax
        # Característica: Fracción de ítems empacables.
        frac_packable = fits.sum() / n
        # Peso medio de los ítems empacables.
        mean_w_pack = w[fits].mean()
    else:
        max_ratio_pack = std_ratio_pack = frac_packable = 0.0
        mean_w_pack = 1.0

    # Característica: Tightness (estrechez), relación entre la capacidad y el peso total de los ítems restantes.
    tightness = cap / w.sum() if w.sum() > 0 else 0.0
    # Característica: Fill (llenado), fracción de la capacidad inicial ya ocupada.
    fill = 1.0 - cap / state.initial_capacity
    # Característica: Slack per item (holgura por ítem), capacidad restante dividida por el peso medio
    # de los ítems empacables, normalizada por el número de ítems.
    slack_per_item = (cap / mean_w_pack) / n if mean_w_pack > 0 else 0.0
    # Característica: Fracción de ítems restantes respecto al total inicial.
    return [r.mean() / rmax, max_ratio_pack, std_ratio_pack,
            frac_packable, tightness, fill, slack_per_item,
            n / state.n_items]


# ----------------------------------------------------------------------
# Construcción del dataset (rollout como oráculo de etiquetado)
# ----------------------------------------------------------------------
def list_instances(folder: str) -> list[str]:
    """Lista los archivos de instancia de la mochila en una carpeta dada.

    Args:
        folder (str): La ruta de la carpeta.

    Returns:
        list[str]: Una lista ordenada de nombres de archivo de instancia (.kp).
    """
    return sorted(f for f in os.listdir(folder) if f.endswith(".kp"))


def build_rollout_dataset(folder: str, samples: int | None = None,
                          seed: int = SEED,
                          base: str = "MAXPW") -> pd.DataFrame:
    """Construye un dataset etiquetando cada estado visitado con la heurística seleccionada por el rollout.

    Las instancias se barajan con una semilla fija antes del submuestreo
    para que el subconjunto de entrenamiento no esté sesgado por el orden de los nombres de archivo.

    Args:
        folder (str): Carpeta que contiene las instancias del problema.
        samples (int | None): Número de instancias a usar para el entrenamiento (si es None, usa todas).
        seed (int): Semilla para la aleatoriedad.
        base (str): Heurística base para la política de rollout.

    Returns:
        pd.DataFrame: Un DataFrame con las características del estado y la heurística óptima ('BEST_H').
    """
    files = list_instances(folder)
    # Si se especifica un número de muestras, baraja y selecciona.
    if samples is not None and samples < len(files):
        random.Random(seed).shuffle(files)
        files = files[:samples]

    rows = []
    for fname in files:
        state = KnapsackState.from_file(os.path.join(folder, fname)) # Carga la instancia.
        while state.remaining.any(): # Itera hasta que no queden ítems por empacar.
            feats = step_features(state) # Calcula las características del estado actual.
            # Etiqueta con desempate a favor de la base: si varias heurísticas
            # empatan en beneficio simulado, la etiqueta es la base (MAXPW).
            h = rollout_choice(state, base, prefer_base_on_ties=True)
            # Agrega una fila al dataset con las características y la heurística elegida.
            rows.append(dict(zip(FEATURE_NAMES, feats), BEST_H=h))
            item = state.next_item(h) # Selecciona el ítem según la heurística.
            if item == -1: # Si no se puede empacar más ítems.
                break
            state.pack(item) # Empaca el ítem.
    return pd.DataFrame(rows)


# ----------------------------------------------------------------------
# Random Forest Hyper-Heuristic (RF-HH)
# ----------------------------------------------------------------------
def train_rf(df: pd.DataFrame) -> RandomForestClassifier:
    """Entrena un modelo Random Forest usando el dataset generado.

    Args:
        df (pd.DataFrame): El DataFrame de entrenamiento con características y etiquetas.

    Returns:
        RandomForestClassifier: El modelo de Random Forest entrenado.
    """
    X = df[FEATURE_NAMES].values # Características (inputs) del modelo.
    y = df["BEST_H"].map(H_TO_IDX).values # Etiquetas (outputs) del modelo, mapeadas a índices numéricos.
    model = RandomForestClassifier(
        n_estimators=N_ESTIMATORS, # Número de árboles en el bosque.
        min_samples_leaf=MIN_SAMPLES_LEAF, # Mínimo de muestras por hoja.
        random_state=SEED, # Semilla para reproducibilidad.
        n_jobs=1,  # 1 núcleo: evita el overhead de joblib en predicciones de una sola muestra.
    )
    model.fit(X, y) # Entrena el modelo.
    return model


def solve_rf_hh(state: KnapsackState, model: RandomForestClassifier,
                threshold: float = CONFIDENCE_THRESHOLD) -> int:
    """Solucionador RF-HH con fallback a MAXPW basado en el umbral de confianza.

    Cuando la probabilidad de la clase principal predicha por el clasificador está por debajo del `threshold`,
    se usa la heurística segura por defecto, MAXPW. Esto protege contra predicciones de baja confianza
    en estados que no están bien cubiertos por los datos de entrenamiento.

    Args:
        state (KnapsackState): El estado actual del problema de la mochila.
        model (RandomForestClassifier): El modelo de Random Forest entrenado.
        threshold (float): Umbral de confianza para el fallback.

    Returns:
        int: El beneficio final obtenido.
    """
    classes = list(model.classes_) # Clases (heurísticas) que el modelo puede predecir.
    while state.remaining.any(): # Mientras queden ítems por considerar.
        feats = np.array([step_features(state)]) # Calcula las características para el estado actual.
        proba = model.predict_proba(feats)[0] # Obtiene las probabilidades de predicción para cada heurística.
        k = int(np.argmax(proba)) # Índice de la heurística con mayor probabilidad.
        h_idx = classes[k] # Índice de la heurística predicha.
        # Si la confianza es baja Y la heurística NO es MAXPW, se fuerza a MAXPW (fallback).
        if h_idx != MAXPW_IDX and proba[k] < threshold:
            h_idx = MAXPW_IDX
        item = state.next_item(HEURISTICS[h_idx]) # Obtiene el ítem seleccionado por la heurística (predicha o fallback).
        if item == -1: # Si no se puede empacar más ítems.
            break
        state.pack(item) # Empaca el ítem.
    return state.profit


def solve_rf_hh_batch(states: list[KnapsackState],
                      model: RandomForestClassifier,
                      threshold: float = CONFIDENCE_THRESHOLD) -> list[int]:
    """Resuelve muchas instancias en paralelo con una sola llamada a `predict_proba` por paso.

    Produce exactamente las mismas soluciones que `solve_rf_hh`; el procesamiento por lotes solo
    amortiza la sobrecarga por llamada del predictor de scikit-learn (una llamada de una sola fila cuesta casi lo mismo
    que una llamada de varios cientos de filas), por lo que el rendimiento mejora en órdenes de magnitud.

    Args:
        states (list[KnapsackState]): Lista de estados del problema de la mochila.
        model (RandomForestClassifier): El modelo de Random Forest entrenado.
        threshold (float): Umbral de confianza para el fallback.

    Returns:
        list[int]: Una lista con los beneficios finales obtenidos para cada instancia.
    """
    classes = list(model.classes_)
    # `active` guarda los índices de las instancias que aún tienen ítems restantes.
    active = [i for i, s in enumerate(states) if s.remaining.any()]
    while active:
        # Calcula las características para todos los estados activos en un solo lote.
        feats = np.array([step_features(states[i]) for i in active])
        probas = model.predict_proba(feats) # Predice las probabilidades para todo el lote.
        still_active = []
        for row, i in enumerate(active):
            s = states[i]
            proba = probas[row]
            k = int(np.argmax(proba))
            h_idx = classes[k]
            # Aplica la lógica de fallback como en `solve_rf_hh`.
            if h_idx != MAXPW_IDX and proba[k] < threshold:
                h_idx = MAXPW_IDX
            item = s.next_item(HEURISTICS[h_idx])
            if item == -1:
                continue
            s.pack(item)
            if s.remaining.any(): # Si esta instancia aún tiene ítems restantes, la añade a la lista de `still_active`.
                still_active.append(i)
        active = still_active # Actualiza la lista de instancias activas.
    return [s.profit for s in states]


# ----------------------------------------------------------------------
# Evaluación
# ----------------------------------------------------------------------
def instance_category(filename: str) -> str:
    """Extrae la categoría de dificultad y la heurística generadora del nombre de archivo de la instancia.

    Args:
        filename (str): El nombre del archivo de la instancia.

    Returns:
        str: Una cadena que describe la categoría (ej. 'DEF_EASY', 'MAXPW_HARD').
    """
    for h in HEURISTICS:
        for d in ("EASY", "HARD"):
            if f"{h}_{d}" in filename:
                return f"{h}_{d}"
    return "OTHER"


def evaluate(test_folder: str, model: RandomForestClassifier,
             outdir: str) -> tuple[pd.DataFrame, float, float]:
    """Evalúa el rendimiento de las diferentes heurísticas y del RF-HH en un conjunto de prueba.

    Genera estadísticas de rendimiento y figuras.

    Args:
        test_folder (str): Carpeta con las instancias de prueba.
        model (RandomForestClassifier): El modelo RF-HH entrenado.
        outdir (str): Directorio donde se guardarán las figuras.

    Returns:
        tuple[pd.DataFrame, float, float]: DataFrame con los resultados de profit
            por instancia, tiempo medio por instancia del rollout y del RF-HH.
    """
    files = list_instances(test_folder)
    rows, rollout_times = [], []
    # Listas para guardar las decisiones del primer paso para la matriz de confusión.
    oracle_first, rf_first = [], []

    for fname in files:
        path = os.path.join(test_folder, fname)
        # Inicializa la fila de resultados para la instancia actual.
        row = {"Filename": fname,
               "Category": "HARD" if "HARD" in fname else "EASY",
               "Type": instance_category(fname)}

        # Resuelve la instancia con cada heurística estática.
        for h in HEURISTICS:
            row[h] = KnapsackState.from_file(path).solve_static(h)

        # Resuelve la instancia con la política de rollout y mide el tiempo.
        state = KnapsackState.from_file(path)
        t0 = time.perf_counter()
        row["Rollout"] = solve_rollout(state)
        rollout_times.append(time.perf_counter() - t0)

        # Registra las decisiones del primer paso para el análisis de la matriz de confusión.
        state = KnapsackState.from_file(path)
        oracle_first.append(H_TO_IDX[rollout_choice(state)]) # La "verdad" del rollout.
        rf_first.append(int(model.predict(
            np.array([step_features(state)]))[0])) # La predicción del RF-HH.

        rows.append(row)

    # RF-HH: evaluación por lotes (soluciones idénticas, sobrecarga amortizada)
    # Prepara los estados de todas las instancias para la evaluación por lotes.
    states = [KnapsackState.from_file(os.path.join(test_folder, f))
              for f in files]
    t0 = time.perf_counter() # Mide el tiempo de ejecución del RF-HH por lotes.
    rf_profits = solve_rf_hh_batch(states, model)
    rf_total = time.perf_counter() - t0
    # Asigna los profits obtenidos por RF-HH a las filas correspondientes.
    for row, prof in zip(rows, rf_profits):
        row["RF-HH"] = prof

    df = pd.DataFrame(rows) # Crea el DataFrame final de resultados.

    # ---- Resumen de resultados ------------------------------------------
    methods = HEURISTICS + ["Rollout", "RF-HH"]
    print("\n=== Beneficio medio (N={}) ===".format(len(df)))
    print(df[methods].mean().round(2).to_string()) # Muestra el beneficio medio de cada método.

    # Realiza la prueba de Wilcoxon para comparar Rollout vs MAXPW.
    stat, p = wilcoxon(df["Rollout"], df["MAXPW"])
    wins = int((df["Rollout"] > df["MAXPW"]).sum()) # Cuenta las victorias de Rollout.
    print(f"\nWilcoxon Rollout vs MAXPW: p = {p:.3e}, "
          f"victorias {wins}/{len(df)} ({100 * wins / len(df):.1f}%) -- Cuántas veces Rollout fue mejor que MAXPW")

    # Realiza la prueba de Wilcoxon para comparar RF-HH vs MAXPW.
    stat2, p2 = wilcoxon(df["RF-HH"], df["MAXPW"])
    wins2 = int((df["RF-HH"] > df["MAXPW"]).sum()) # Cuenta las victorias de RF-HH.
    print(f"Wilcoxon RF-HH  vs MAXPW: p = {p2:.3e}, "
          f"victorias {wins2}/{len(df)} ({100 * wins2 / len(df):.1f}%) -- Cuántas veces RF-HH fue mejor que MAXPW")

    avg_rollout_time = np.mean(rollout_times)
    avg_rfhh_time = rf_total / len(df)
    print(f"\nTiempo medio/instancia: rollout {avg_rollout_time:.4f}s, "
          f"RF-HH (por lotes) {avg_rfhh_time:.4f}s")
    # Calcula qué porcentaje del beneficio del rollout el RF-HH logra capturar.
    ratio = df['RF-HH'].mean() / df['Rollout'].mean()
    print(f"RF-HH captura el {100 * ratio:.1f}% del beneficio del rollout")

    # Genera y guarda todas las figuras de visualización.
    make_figures(df, model, oracle_first, rf_first, outdir)
    print(f"Figuras escritas en {outdir}/")

    return df, avg_rollout_time, avg_rfhh_time


# ----------------------------------------------------------------------
# Figuras (todas guardadas a 300 dpi en `outdir`)
# ----------------------------------------------------------------------
def make_figures(df, model, oracle_first, rf_first, outdir):
    """Genera varias figuras para visualizar los resultados y las guarda en el directorio especificado.

    Args:
        df (pd.DataFrame): DataFrame con los resultados de profit.
        model (RandomForestClassifier): El modelo RF-HH entrenado.
        oracle_first (list): Decisiones del primer paso del oráculo (rollout).
        rf_first (list): Decisiones del primer paso del RF-HH.
        outdir (str): Directorio donde se guardarán las figuras.
    """
    os.makedirs(outdir, exist_ok=True) # Crea el directorio de salida si no existe.
    methods = HEURISTICS + ["Rollout", "RF-HH"]
    sns.set_style("whitegrid") # Establece el estilo de las gráficas de seaborn.

    # Fig 2: Diagrama de cajas (boxplot) de los profits de cada método.
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df[methods], palette="viridis")
    plt.xlabel("Método")
    plt.ylabel("Beneficio")
    plt.savefig(os.path.join(outdir, "boxplot.png"), **FIG_KW)
    plt.close() # Cierra la figura para liberar memoria.

    # Fig 3: Gráfico de dispersión (scatter) de MAXPW vs Rollout.
    plt.figure(figsize=(8, 8))
    # Define los límites para los ejes, asegurando que cubran todos los datos.
    lims = [min(df["MAXPW"].min(), df["Rollout"].min()),
            max(df["MAXPW"].max(), df["Rollout"].max())]
    plt.scatter(df["MAXPW"], df["Rollout"], alpha=0.5, color="#2a788e")
    plt.plot(lims, lims, "r--", alpha=0.75, label="x = y") # Línea de referencia donde ambos métodos son iguales.
    plt.xlabel("Beneficio MAXPW")
    plt.ylabel("Beneficio Rollout")
    plt.legend()
    plt.savefig(os.path.join(outdir, "scatter.png"), **FIG_KW)
    plt.close()

    # Fig 4: Distribuciones de profit de MAXPW y RF-HH.
    plt.figure(figsize=(10, 6))
    sns.kdeplot(df["MAXPW"], fill=True, label="MAXPW", color="blue")
    sns.kdeplot(df["RF-HH"], fill=True, label="RF-HH", color="green")
    plt.xlabel("Beneficio")
    plt.ylabel("Densidad")
    plt.legend()
    plt.savefig(os.path.join(outdir, "distribution.png"), **FIG_KW)
    plt.close()

    # Fig 5: Mapa de calor (heatmap) de las elecciones de heurística en el primer paso por tipo de instancia.
    hm = pd.DataFrame({
        "Type": df["Type"],
        "Heuristic": [HEURISTICS[i] for i in oracle_first], # Convierte índices a nombres de heurísticas.
    })
    # Calcula las frecuencias de cada heurística por tipo de instancia.
    counts = hm.groupby(["Type", "Heuristic"]).size().unstack(fill_value=0)
    plt.figure(figsize=(10, 6))
    sns.heatmap(counts, annot=True, fmt="d", cmap="YlGnBu") # `annot=True` muestra los valores en las celdas.
    plt.xlabel("Heurística seleccionada por el rollout")
    plt.ylabel("Tipo de instancia")
    plt.savefig(os.path.join(outdir, "heatmap.png"), **FIG_KW)
    plt.close()

    # Fig 6: trayectoria de profit acumulado en una instancia representativa (se omite en el CLI).
    # (resolver la primera instancia paso a paso)
    # Se deja al notebook si es necesario; omitido aquí para la brevedad del CLI.

    # Fig 7: Importancia de las características (feature importances) del modelo RF-HH.
    imp = model.feature_importances_ # Obtiene la importancia de cada característica.
    order = np.argsort(imp) # Ordena las características por importancia.
    plt.figure(figsize=(10, 6))
    # Crea un gráfico de barras horizontales mostrando la importancia.
    plt.barh(range(len(order)), imp[order], color="#2a788e")
    plt.yticks(range(len(order)), [FEATURE_NAMES[i] for i in order]) # Nombres de las características en el eje Y.
    plt.xlabel("Importancia relativa")
    plt.tight_layout() # Ajusta el diseño para evitar solapamientos.
    plt.savefig(os.path.join(outdir, "feature_importance.png"), **FIG_KW)
    plt.close()

    # Fig 8: Matriz de confusión (decisiones del primer paso en el conjunto de prueba).
    # Compara las decisiones del primer paso del Rollout (oráculo) con las del RF-HH.
    labels = np.unique(np.concatenate([oracle_first, rf_first])) # Obtiene todas las etiquetas únicas.
    cm = confusion_matrix(
        oracle_first, rf_first, labels=labels) # Calcula la matriz de confusión.
    disp = ConfusionMatrixDisplay(
        cm, display_labels=[HEURISTICS[i] for i in labels]) # Prepara la visualización.
    fig, ax = plt.subplots(figsize=(8, 8))
    disp.plot(cmap="Blues", ax=ax, colorbar=False)
    plt.savefig(os.path.join(outdir, "confusion_matrix.png"), **FIG_KW)
    plt.close()

    # Fig 9: Comparación del rendimiento por dificultad (EASY/HARD).
    diff = (df.groupby("Category")[["MAXPW", "Rollout", "RF-HH"]]
              .mean().reset_index()
              .melt(id_vars="Category", var_name="Method",
                    value_name="Mean Profit")) # Agrupa, calcula el promedio y transforma el formato.
    plt.figure(figsize=(10, 6))
    sns.barplot(x="Category", y="Mean Profit", hue="Method",
                data=diff, palette="viridis") # Crea un gráfico de barras.
    plt.savefig(os.path.join(outdir, "difficulty_comparison.png"), **FIG_KW)
    plt.close()

    print(f"Figuras escritas en {outdir}/")


# ----------------------------------------------------------------------
# Función principal (main) - Uso desde línea de comandos
# ----------------------------------------------------------------------
def main():
    # Configura el analizador de argumentos de línea de comandos.
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--train", required=True, help="carpeta de instancias de entrenamiento")
    ap.add_argument("--test", required=True, help="carpeta de instancias de prueba")
    ap.add_argument("--samples", type=int, default=200,
                    help="número de instancias de entrenamiento a etiquetar con el rollout")
    ap.add_argument("--seed", type=int, default=SEED, help="semilla para la aleatoriedad")
    ap.add_argument("--outdir", default="figures", help="directorio de salida para las figuras")
    ap.add_argument("--results-csv", default="results.csv", help="nombre del archivo CSV para los resultados")
    args = ap.parse_args()

    # Establece las semillas para NumPy y el módulo random de Python.
    np.random.seed(args.seed)
    random.seed(args.seed)

    print(f"1/3 Construyendo el dataset etiquetado por rollout "
          f"({args.samples} instancias, semilla {args.seed})...")
    t0 = time.perf_counter() # Inicia la medición del tiempo.
    df_train = build_rollout_dataset(args.train, samples=args.samples,
                                     seed=args.seed)
    print(f"    {len(df_train)} transiciones en "
          f"{time.perf_counter() - t0:.1f}s") # Muestra el tiempo transcurrido.
    print("    Distribución de etiquetas:")
    print(df_train["BEST_H"].value_counts().to_string()) # Muestra cuántas veces se eligió cada heurística.

    print("2/3 Entrenando Random Forest...")
    model = train_rf(df_train)

    print("3/3 Evaluando en el conjunto de prueba...")
    df, avg_rollout_time, avg_rfhh_time = evaluate(args.test, model, args.outdir)
    df.to_csv(args.results_csv, index=False) # Guarda los resultados en un archivo CSV.
    print(f"Resultados por instancia guardados en {args.results_csv}")


# Punto de entrada estándar: solo ejecuta main() cuando el archivo
# se corre como script (python nextgenfinal1.py --train ... --test ...),
# no cuando se importa como módulo.
if __name__ == "__main__":
    main()
